---
name: Eden_setup
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: setup
        run: |
          sudo apt update
          sudo apt install -y qemu-utils qemu-user-static
      - name: host info
        run: |
          ip a
      - name: get eden
        uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: build docker images
        run: |
          make LINUXKIT_TARGET=build DOCKER_PLATFORM=linux/arm64 build-docker
          make LINUXKIT_TARGET=build DOCKER_PLATFORM=linux/amd64 build-docker
  setup:
    runs-on: self-hosted
    steps:
      - name: setup
        run: |
          sudo apt update
          sudo apt install -y qemu-utils qemu-user-static qemu-system-x86 jq swtpm
      - name: host info
        run: |
          ip a
      - name: get eden
        uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: build eden
        run: |
          make clean
          make build-tests
      - name: run
        run: |
          # check separate (non-default) config
          ./eden config add setup
          ./eden config set setup --key=eve.accel --value=false
          ./eden --config setup setup
          ./eden --config setup start
          ./eden --config setup eve onboard
          ./eden --config setup info
          ./eden --config setup clean

          ./eden config add setup --arch=arm64
          ./eden --config setup setup
          ./eden --config setup clean
          ./eden config delete setup
          ./eden config add setup --devmodel GCP
          ./eden --config setup setup
          ./eden --config setup clean
          ./eden config delete setup

          ./eden config add setup --devmodel RPi4
          ./eden --config setup setup
          ./eden --config setup clean
          ./eden config delete setup
          ./eden config add setup --devmodel general
          ./eden --config setup setup
          ./eden --config setup clean
          ./eden config delete setup

          # try download and build from repo
          ./eden config add setup
          # use stable tag as eve tag and branch may differ
          ./eden config set setup --key eve.tag --value="8.6.0"
          ./eden --config setup setup --download=false
          ./eden --config setup clean
          ./eden config delete setup
