---
name: Publish DockerHub
# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  check-secrets:
    runs-on: ubuntu-22.04
    outputs:
      available: ${{ steps.secrets.outputs.defined }}
    steps:
      - id: secrets
        if: ${{ env.DOCKERHUB_TOKEN != '' }}
        run: echo "defined=true" >> $GITHUB_OUTPUT
        env:
          DOCKERHUB_TOKEN: ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}
  build:
    runs-on: ubuntu-22.04
    needs: [check-secrets]
    if: needs.check-secrets.outputs.available == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to DockerHUB
        id: login
        run: |
          echo "${{ secrets.RELEASE_DOCKERHUB_TOKEN }}" |\
             docker login -u "${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}" --password-stdin
      - name: Build and push
        run: |
          make DOCKER_TARGET=push LINUXKIT_TARGET=push DOCKER_PLATFORM=linux/arm64,linux/amd64 build-docker
