---
name: Static validation
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]

jobs:
  yetus:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: make validate
        run: |
          make validate
